name: ido
description: A starting point for Dart libraries or applications.
version: 0.1.0+2
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  buffer: ^1.1.1
  http_parser: ^4.0.0
  balance_http: ^0.1.0
    #path: ../balance_http
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
